# Generated by Django 2.2.4 on 2019-08-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190822_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['publish_date', 'updated', 'timestamp']},
        ),
    ]
