# Generated by Django 2.2.4 on 2019-08-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190822_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['pk', '-publish_date', '-updated', '-timestamp']},
        ),
    ]
